create tablespace IMDL_DATA_01 DATAFILE 'G:\oradata\GLDBDEV\IMDL_DATA.dbf' 
SIZE 1024M REUSE AUTOEXTEND ON NEXT  256M MAXSIZE  4096M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
create tablespace IMDL_INDEX_01 DATAFILE 'G:\oradata\GLDBDEV\IMDL_INDEX.dbf' 
SIZE 1024M REUSE AUTOEXTEND ON NEXT  256M MAXSIZE  4096M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;

create tablespace SMDL_DATA_01 DATAFILE 'G:\oradata\GLDBDEV\SMDL_DATA.dbf' 
SIZE 1024M REUSE AUTOEXTEND ON NEXT  256M MAXSIZE  4096M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
create tablespace SMDL_INDEX_01 DATAFILE 'G:\oradata\GLDBDEV\SMDL_INDEX.dbf' 
SIZE 1024M REUSE AUTOEXTEND ON NEXT  256M MAXSIZE  4096M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;

create tablespace IPSM_DATA_01 DATAFILE 'G:\oradata\GLDBDEV\IPSM_DATA.dbf' 
SIZE 1024M REUSE AUTOEXTEND ON NEXT  256M MAXSIZE  4096M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
create tablespace IPSM_INDEX_01 DATAFILE 'G:\oradata\GLDBDEV\IPSM_INDEX.dbf' 
SIZE 1024M REUSE AUTOEXTEND ON NEXT  256M MAXSIZE  4096M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;